### ISSUE TITLE
Theoretical Azimuth calculation

### ISSUE THREAD

**Issue by xMikeTx** [lycha/augmented-reality-example#1]
Thanx for the nice tutorial.

I think it would be better to use the Location.bearingTo() method to calculate the theoretical azimuth.
Its easier and a lot more comprehensive.

Although from a teaching point of view, your approach is easier to understand.

cheers

**Comment by lycha** [comment]
Hi, thanks for comment! It's great you've enjoyed my tutorial. There is plenty ways to get bearing or GPS location. It also depends on the hardware you have. For sure there are better ways to achieve it but my goal was to make it as transparent as possible to allow easy transition to other platforms. 

Good luck with coding!
